### PR TITLE
add dep support

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by tamird** [comment]
LGTM mod the code repetition. Shouldn't this just be a matter of substituting yaml for toml in one place?

---

Reviewed 46 of 47 files at r1.
Review status: 45 of 46 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/dep-diff-parser/main.go, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yEb2AE1UH5dEuGg9:-Kn0yEb3hLvTkOF5LAmm:b364fbz) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/dep-diff-parser/main.go#L21)):*
> ```Go
> 		}
> 	}{}
> 	err := toml.Unmarshal(content, &l)
> ```

reduce scope

---

*[cmd/dep-diff-parser/main.go, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yPztLtFWx9ZeQDld:-Kn0yPztLtFWx9ZeQDle:bwewqf) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/dep-diff-parser/main.go#L43)):*
> ```Go
> 	}
> 	if err := lockfile.SummarizeDiff(args, *verbose, lockfileName, parseDepTOML); err != nil {
> 		fmt.Fprintf(os.Stderr, "%+v", err)
> ```

+v doesn't do what you want (see https://github.com/cockroachdb/cockroach/pull/16558/commits/0d3325cc1b174578f2866abef69be3145f0e09d5); I'd just use `log.Fatal(err)` here.

---

*[cmd/glide-diff-parser/main.go, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yhxXV7qO1J5I2veE:-Kn0yhxXV7qO1J5I2veF:bwhmeli) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/glide-diff-parser/main.go#L22)):*
> ```Go
> 		}
> 	}{}
> 	err := yaml.Unmarshal(content, &l)
> ```

scope more narrowly. also this is essentially the same method on the toml side; perhaps you could factor out something that takes `func([]byte, interface{}) error`?

---

*[cmd/glide-diff-parser/main.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yqrQyevYQmss3DNe:-Kn0yqrQyevYQmss3DNf:b-7ropln) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/glide-diff-parser/main.go#L44)):*
> ```Go
> 	}
> 	if err := lockfile.SummarizeDiff(args, *verbose, lockfileName, parseGlildeYAML); err != nil {
> 		fmt.Fprintf(os.Stderr, "%+v", err)
> ```

ditto

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-:-Kn0yvSxCkdKhF_BwgMg:b-oxlpy0)*

**Comment by dt** [comment]
Review status: 4 of 46 files reviewed at latest revision, 4 unresolved discussions.

---

*[cmd/dep-diff-parser/main.go, line 21 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yEb2AE1UH5dEuGg9:-Kn1JQwnW53zwTcyZkma:b-896fix) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/dep-diff-parser/main.go#L21)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

reduce scope
</blockquote></details>

Done.

---

*[cmd/dep-diff-parser/main.go, line 43 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yPztLtFWx9ZeQDld:-Kn1J9EI7bNVN75I9m-L:bj15qvx) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/dep-diff-parser/main.go#L43)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

+v doesn't do what you want (see https://github.com/cockroachdb/cockroach/pull/16558/commits/0d3325cc1b174578f2866abef69be3145f0e09d5); I'd just use `log.Fatal(err)` here.
</blockquote></details>

Huh, thanks.
Done.

---

*[cmd/glide-diff-parser/main.go, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yhxXV7qO1J5I2veE:-Kn1JSJkWL4fB9XTOJam:bocurax) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/glide-diff-parser/main.go#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

scope more narrowly. also this is essentially the same method on the toml side; perhaps you could factor out something that takes `func([]byte, interface{}) error`?
</blockquote></details>

Done (scope).

Hmm, I not sure they can share the struct def though, or even should: different field names could be maybe hacked around with tags but representing potentially different structure, like branch or tag info, could get messy. I think I like `[]lockfile.Version` as the common, tool independent representation of a version resolution, and then leaving this part to the tool-specific frontends.

---

*[cmd/glide-diff-parser/main.go, line 44 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yqrQyevYQmss3DNe:-Kn1JS1ZitffGmQFLxqr:b-896fix) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/glide-diff-parser/main.go#L44)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2)*

**Comment by tamird** [comment]
Reviewed 1 of 47 files at r1, 42 of 42 files at r2, 41 of 41 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/glide-diff-parser/main.go, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yhxXV7qO1J5I2veE:-Kn1Tt-huN8DK_aE_bMW:bgk40cb) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/glide-diff-parser/main.go#L22)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

Done (scope).

Hmm, I not sure they can share the struct def though, or even should: different field names could be maybe hacked around with tags but representing potentially different structure, like branch or tag info, could get messy. I think I like `[]lockfile.Version` as the common, tool independent representation of a version resolution, and then leaving this part to the tool-specific frontends.
</blockquote></details>

I mean it's also the case that they don't need to share the struct def; that's also something that could be passed in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2)*

**Comment by dt** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/glide-diff-parser/main.go, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yhxXV7qO1J5I2veE:-Kn1aF_P29sB8JN1o3rg:b-2zquyq) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/glide-diff-parser/main.go#L22)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I mean it's also the case that they don't need to share the struct def; that's also something that could be passed in.
</blockquote></details>

not sure I follow what's being suggested -- if caller is defining a struct and and an unmarshal func, there's not really anything left to pull into a common helper.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2)*

**Comment by tamird** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/glide-diff-parser/main.go, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-Kn0yhxXV7qO1J5I2veE:-Kn1qm_UIVPGRmLZDJuI:blvxrgb) ([raw file](https://github.com/cockroachdb/glide-diff-parser/blob/f14490f84bf93faa41b5640f28e323bcaf904023/cmd/glide-diff-parser/main.go#L22)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

not sure I follow what's being suggested -- if caller is defining a struct and and an unmarshal func, there's not really anything left to pull into a common helper.
</blockquote></details>

Ah, I misunderstood the amount of code being duplicated; looks fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/glide-diff-parser/2#-:-Kn1qqj9RH2ZIFwqZkNM:bnfp4nl)*

**Pull request merged**
